// ─── IUCN Conservation Status ─────────────────────────────────
// Codes: LC=Least Concern, NT=Near Threatened, VU=Vulnerable,
//        EN=Endangered, CR=Critically Endangered, DD=Data Deficient
// LC and DD are hidden in the UI; the others show as coloured chips.

const CONSERVATION = {
  // Felines
  "jaguar":                          "NT",
  "puma":                            "LC",
  "ocelot":                          "LC",
  "margay":                          "NT",
  "oncilla":                         "VU",
  "jaguarundi":                      "LC",
  // Canines
  "maned-wolf":                      "NT",
  "crab-eating-fox":                 "LC",
  "bush-dog":                        "NT",
  // Mustelids
  "giant-otter":                     "EN",
  "neotropical-river-otter":         "NT",
  "greater-grison":                  "LC",
  "tayra":                           "LC",
  // Procyonids
  "south-american-coati":            "LC",
  "crab-eating-raccoon":             "LC",
  "kinkajou":                        "LC",
  // Primates
  "black-howler-monkey":             "LC",
  "azaras-night-monkey":             "LC",
  "black-tailed-marmoset":           "LC",
  "golden-lion-tamarin":             "EN",
  "brown-howler-monkey":             "EN",
  "brown-capuchin":                  "LC",
  "southern-muriqui":                "CR",
  "common-marmoset":                 "LC",
  "buffy-tufted-ear-marmoset":       "CR",
  "masked-titi":                     "VU",
  // Anteaters
  "giant-anteater":                  "VU",
  "southern-tamandua":               "LC",
  "silky-anteater":                  "LC",
  // Armadillos
  "giant-armadillo":                 "VU",
  "nine-banded-armadillo":           "LC",
  "six-banded-armadillo":            "LC",
  "southern-three-banded-armadillo": "VU",
  "southern-naked-tailed-armadillo": "LC",
  // Ungulates
  "south-american-tapir":            "VU",
  "white-lipped-peccary":            "VU",
  "collared-peccary":                "LC",
  "marsh-deer":                      "VU",
  "pampas-deer":                     "NT",
  "red-brocket-deer":                "DD",
  "small-red-brocket-deer":          "EN",
  // Cetaceans
  "amazon-river-dolphin":            "EN",
  "tucuxi":                          "EN",
  // Rodents
  "capybara":                        "LC",
  "spotted-paca":                    "LC",
  "azaras-agouti":                   "LC",
  "red-rumped-agouti":               "LC",
  "coypu":                           "LC",
  "brazilian-porcupine":             "LC",
  "guianan-squirrel":                "LC",
  "marsh-rice-rat":                  "LC",
  // Opossums
  "white-eared-opossum":             "LC",
  "big-eared-opossum":               "LC",
  "lutrine-opossum":                 "LC",
  "southeastern-four-eyed-opossum":  "LC",
  "gracile-mouse-opossum":           "LC",
  // Bats
  "greater-bulldog-bat":             "LC",
  "common-vampire-bat":              "LC",
  "pallass-long-tongued-bat":        "LC",
  "great-fruit-eating-bat":          "LC",
  "lesser-spear-nosed-bat":          "LC",
  // Birds — Macaws & Parrots
  "hyacinth-macaw":                  "VU",
  "red-and-green-macaw":             "LC",
  "blue-fronted-amazon":             "LC",
  "red-browed-amazon":               "EN",
  "peach-fronted-parakeet":          "LC",
  // Birds — Toucans
  "toco-toucan":                     "LC",
  "saffron-toucanet":                "NT",
  "chestnut-eared-aracari":          "LC",
  // Birds — Raptors
  "snail-kite":                      "LC",
  "savanna-hawk":                    "LC",
  "black-collared-hawk":             "LC",
  "harpy-eagle":                     "VU",
  // Birds — Wading Birds
  "jabiru-stork":                    "LC",
  "roseate-spoonbill":               "LC",
  "cocoi-heron":                     "LC",
  "wattled-jacana":                  "LC",
  "sunbittern":                      "LC",
  // Birds — Hummingbirds
  "swallow-tailed-hummingbird":      "LC",
  "black-jacobin":                   "LC",
  "violet-capped-woodnymph":         "LC",
  // Birds — Cracids
  "bare-faced-curassow":             "VU",
  "chestnut-bellied-guan":           "VU",
  "black-fronted-piping-guan":       "EN",
  // Birds — Waterfowl & Screamers
  "southern-screamer":               "LC",
  "anhinga":                         "LC",
  "greater-rhea":                    "NT",
  // Birds — Kingfishers
  "ringed-kingfisher":               "LC",
  "amazon-kingfisher":               "LC",
  // Birds — Tanagers & Songbirds
  "brazilian-tanager":               "LC",
  "red-necked-tanager":              "LC",
  "blue-dacnis":                     "LC",
  "bare-throated-bellbird":          "NT",
  // Birds — Nightbirds & Manakins
  "great-potoo":                     "LC",
  "white-bearded-manakin":           "LC",
  // Reptiles
  "yacare-caiman":                   "LC",
  "broad-snouted-caiman":            "LC",
  "green-anaconda":                  "LC",
  "yellow-anaconda":                 "LC",
  "boa-constrictor":                 "LC",
  "brazilian-rainbow-boa":           "LC",
  "vine-snake":                      "LC",
  "false-water-cobra":               "LC",
  "mussurana":                       "LC",
  "fer-de-lance":                    "LC",
  "pantanal-lancehead":              "LC",
  "south-american-rattlesnake":      "LC",
  "black-and-white-tegu":            "LC",
  "caiman-lizard":                   "LC",
  "green-iguana":                    "LC",
  "south-american-racerunner":       "LC",
  "tropical-gecko":                  "LC",
  "red-footed-tortoise":             "VU",
  "giant-south-american-river-turtle":"VU",
  "matamata-turtle":                 "LC",
  // Amphibians
  "rococo-toad":                     "LC",
  "cane-toad":                       "LC",
  "pumpkin-toadlet":                 "NT",
  "giant-monkey-frog":               "LC",
  "orange-thighed-monkey-frog":      "LC",
  "clown-tree-frog":                 "LC",
  "golden-tree-frog":                "LC",
  "painted-tree-frog":               "LC",
  "dwarf-monkey-frog":               "LC",
  "smith-frog":                      "LC",
  "common-pantanal-tree-frog":       "LC",
  "south-american-bullfrog":         "LC",
  "paradox-frog":                    "LC",
  "chacoan-horned-frog":             "LC",
  "four-eyed-frog":                  "LC",
  "budgetts-frog":                   "VU",
  "rock-cascade-frog":               "NT",
  "ringed-caecilian":                "LC"
};
